---
# playbook.yml
- name: 'Provision Image'
  hosts: all
  connection: ssh
  gather_facts: yes
  become: yes
  become_user: ubuntu
  become_method: sudo

  tasks:
    - name: install Apache
      package:
        name: 'httpd'
        state: present
